# Generated by Django 5.1 on 2024-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen',
        ),
    ]
